- name: Deploy mongoDB
  docker_container:
    name: mongo
    image: mongo:7.0.7
    ports:
      - 27017:27017
    env:
      - MONGO_INITDB_ROOT_USERNAME: cluster
      - MONGO_INITDB_ROOT_PASSWORD: zFcsT-PQd..e=:,;,GOI-Mp|C=#.;R[Ol)wIf{.DqB:.{BY7-[Zv?;bP{l8zu|Krxab5ezvq;YLe4b[J"s4)TX0z[aUIHomgWX\C4id*X,9*AgWAoOA+7[iTOeZSj9jv.!s2UVQC[,2"8JC3X*x7?)!tOO.kCeKg1F#,e0wzaDu\,ay?JlJbHF8.c0mziLdRcc(wi7KYh"|JuLg.TRtI4p@Ce83hXx=,ZC86FkJ'syuX@qAhpWFh}@f@dA6JYSQzcd[rCc8Aq)f'VdQjp0Sqa[1rbjIf|8e".WAXG{W.S{}-D8q?:-JkuLJ7MX[zl,OilbxlR"c4'1LRabO{Qc:t}:qso0FX4|BFFVLV'cFhfddAE#;q9r}=f0;,HY=z/wPzsmT/k1k4Icx4dBus\Kpp].UE=[I1,Q[[.5;JIj.;3|XDst!d.Edgh6O7twX-Mv@m0=JOpcztH{-k'R}mzRVaKJ3Us'.QS#(DtR!9d9@T37Mhg[#l-wl(f#uzToD.kEWh
    volumes:
      - database:/var/lib/mongo
    restart_policy: on-failure