- name: Deploy registry
  community.docker.docker_container:
    name: registry
    image: registry:2
    volumes:
      - /var/lib/registry:/var/lib/registry
    ports:
      - "5000:5000"
    restart_policy: always
- name: create cronjob
  ansible.builtin.cron:
    name: "clean registry"
    minute: "0"
    hour: "3"
    job: "/usr/bin/docker exec registry /bin/registry garbage-collect /etc/docker/registry/config.yml --delete-untagged=true > ~/clean.out"
