scrape_configs:
  - job_name: "node_exporter"
    scrape_interval: 180s
    static_configs:
      - targets: [
        "k8s-m01:2019",
        "k8s-m02:2019",
        "k8s-m03:2019",
        "k8s-w01:2019",
        "k8s-w02:2019",
        "k8s-w03:2019",
        "k8s-w04:2019",
        "sto-01:2019",
        "haproxy-01:2019"
        "mon-01:2019"
      ]