scrape_configs:
  - job_name: "node_exporter"
    scrape_interval: 180s
    static_configs:
      - targets: [
        "k8s-m01:9100",
        "k8s-m02:9100",
        "k8s-m03:9100",
        "k8s-w01:9100",
        "k8s-w02:9100",
        "k8s-w03:9100",
        "k8s-w04:9100",
        "sto-01:9100",
        "mn-01:9100"
      ]